# https://www.youtube.com/watch?v=rRes9LM-Jh8
# Great tutorial on CI/CD pipeline with github actions, Docker and EC2
name: Docker Image CI

# https://stackoverflow.com/a/64733705
on:
  workflow_run:
    workflows: ["Run tests"]
    branches: [main]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login Dockerhub
        run: echo "Nice"